#!/usr/bin/env Rscript

# =========================================================================
# GSE72810 effect sizes and confidence intervals
# =========================================================================
#
# Purpose
#
# Calculate effect sizes and 95% confidence intervals for the four locked
# GSE72810 analyses generated by Script 47:
#
# 1. Primary fixed-module projection:
#    representative probes, all-146-sample z-reference,
#    23 definite bacterial versus 28 definite viral samples.
#
# 2. Primary-only z-reference sensitivity:
#    the same frozen representative probes,
#    51 definite bacterial and viral samples as the z-reference.
#
# 3. Expanded phenotype sensitivity:
#    40 definite-plus-probable bacterial versus
#    35 definite-plus-probable viral samples.
#
# 4. All-authorized-probe mean sensitivity:
#    all-146-sample z-reference,
#    23 definite bacterial versus 28 definite viral samples.
#
# For every analysis and locked module, this script calculates:
#
# - bacterial and viral group summaries;
# - median bacterial-minus-viral score difference;
# - Hodges-Lehmann location-shift estimate;
# - stratified nonparametric percentile-bootstrap 95% CI for the
#   Hodges-Lehmann estimate;
# - rank-biserial effect size;
# - stratified nonparametric percentile-bootstrap 95% CI for the
#   rank-biserial effect size;
# - Wilcoxon rank-sum P value;
# - within-analysis Benjamini-Hochberg FDR.
#
# Bootstrap resampling is performed independently within bacterial and
# viral groups. The locked modules, sample definitions, probe choices,
# scoring rules and expected directions are not changed.
# =========================================================================


# -------------------------------------------------------------------------
# Package setup
# -------------------------------------------------------------------------

candidate_libs <- unique(
  c(
    Sys.getenv("R_LIBS_USER"),
    path.expand("~/R/library"),
    "env/R_libs",
    .libPaths()
  )
)

candidate_libs <- candidate_libs[
  nzchar(candidate_libs) &
    dir.exists(candidate_libs)
]

if (length(candidate_libs) > 0L) {
  .libPaths(candidate_libs)
}

if (!requireNamespace("data.table", quietly = TRUE)) {
  stop("The data.table package is required.")
}

suppressPackageStartupMessages({
  library(data.table)
})


# -------------------------------------------------------------------------
# Input paths
# -------------------------------------------------------------------------

projection_dir <- paste0(
  "results/revision_round1/",
  "GSE72810_fixed_module_projection"
)

scores_file <- file.path(
  projection_dir,
  "GSE72810_module_scores_long.tsv"
)

reference_tests_file <- file.path(
  projection_dir,
  "GSE72810_primary_and_sensitivity_tests.tsv"
)

analysis_manifest_file <- file.path(
  projection_dir,
  "GSE72810_scoring_analysis_manifest.tsv"
)

coverage_file <- file.path(
  projection_dir,
  "GSE72810_scoring_module_coverage.tsv"
)

projection_quality_summary_file <- file.path(
  projection_dir,
  "GSE72810_projection_quality_summary.tsv"
)


# -------------------------------------------------------------------------
# Output paths
# -------------------------------------------------------------------------

out_dir <- paste0(
  "results/revision_round1/",
  "GSE72810_effect_sizes_confidence_intervals"
)

docs_dir <- "docs/revision_round1"
session_dir <- "env/session_info/revision_round1"

dir.create(
  out_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  docs_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  session_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

effect_results_file <- file.path(
  out_dir,
  "GSE72810_effect_sizes_confidence_intervals.tsv"
)

primary_table_file <- file.path(
  out_dir,
  "GSE72810_primary_effect_sizes_manuscript_table.tsv"
)

bootstrap_manifest_file <- file.path(
  out_dir,
  "GSE72810_effect_size_bootstrap_manifest.tsv"
)

analysis_summary_file <- file.path(
  out_dir,
  "GSE72810_effect_size_analysis_summary.tsv"
)

quality_checks_file <- file.path(
  out_dir,
  "GSE72810_effect_size_quality_gate.tsv"
)

quality_summary_file <- file.path(
  out_dir,
  "GSE72810_effect_size_quality_summary.tsv"
)

report_file <- file.path(
  docs_dir,
  "GSE72810_effect_sizes_confidence_intervals_report.md"
)

session_file <- file.path(
  session_dir,
  "GSE72810_effect_sizes_confidence_intervals_sessionInfo.txt"
)

output_files <- c(
  effect_results_file,
  primary_table_file,
  bootstrap_manifest_file,
  analysis_summary_file,
  quality_checks_file,
  quality_summary_file,
  report_file,
  session_file
)

unlink(
  output_files,
  force = TRUE
)


# -------------------------------------------------------------------------
# Locked constants
# -------------------------------------------------------------------------

expected_module_ids <- c(
  "BACT_M1",
  "BACT_M2",
  "VIR_M1a",
  "VIR_M1b",
  "VIR_M2"
)

expected_analysis_ids <- c(
  "main_representative_all146_z_definite",
  "primary_only_representative_51_z_definite",
  "expanded_representative_all146_z_definite_probable",
  "all_probe_mean_all146_z_definite"
)

expected_analysis_count <- 4L
expected_effect_rows <- 20L
expected_primary_rows <- 5L
expected_score_rows <- 1715L
expected_reference_test_rows <- 20L
expected_manifest_rows <- 4L
expected_coverage_rows <- 5L

bootstrap_replicates <- 10000L
bootstrap_ci_level <- 0.95
bootstrap_alpha <- 1 - bootstrap_ci_level
bootstrap_quantile_type <- 6L
base_seed <- 20260806L

comparison_tolerance <- 1e-12


# -------------------------------------------------------------------------
# Helper functions
# -------------------------------------------------------------------------

require_columns <- function(
  table_object,
  required_columns,
  source_name
) {
  missing_columns <- setdiff(
    required_columns,
    names(table_object)
  )

  if (length(missing_columns) > 0L) {
    stop(
      paste(
        "Missing required columns in",
        source_name,
        ":",
        paste(
          missing_columns,
          collapse = ", "
        )
      )
    )
  }

  invisible(TRUE)
}


coerce_logical_strict <- function(
  values,
  field_name
) {
  if (is.logical(values)) {
    if (anyNA(values)) {
      stop(
        paste(
          field_name,
          "contains missing logical values."
        )
      )
    }

    return(values)
  }

  normalized <- toupper(
    trimws(
      as.character(values)
    )
  )

  allowed_values <- c(
    "TRUE",
    "FALSE",
    "T",
    "F",
    "1",
    "0"
  )

  invalid <- (
    is.na(normalized) |
      !normalized %in%
        allowed_values
  )

  if (any(invalid)) {
    stop(
      paste(
        field_name,
        "contains values that cannot be interpreted as logical."
      )
    )
  }

  normalized %in% c(
    "TRUE",
    "T",
    "1"
  )
}


parse_semicolon_values <- function(value) {
  value <- as.character(value)

  if (
    length(value) == 0L ||
      is.na(value) ||
      !nzchar(trimws(value))
  ) {
    return(character())
  }

  values <- trimws(
    strsplit(
      value,
      ";",
      fixed = TRUE
    )[[1L]]
  )

  unique(
    values[nzchar(values)]
  )
}


normalize_expected_direction <- function(
  direction_value
) {
  value <- tolower(
    trimws(
      as.character(direction_value)
    )
  )

  bacterial_values <- c(
    "higher_in_bacterial",
    "bacterial_higher",
    "higher in bacterial",
    "bacterial-associated",
    "bacterial_associated"
  )

  viral_values <- c(
    "higher_in_viral",
    "viral_higher",
    "higher in viral",
    "viral-associated",
    "viral_associated"
  )

  if (value %in% bacterial_values) {
    return("higher_in_bacterial")
  }

  if (value %in% viral_values) {
    return("higher_in_viral")
  }

  if (
    grepl("bacter", value) &&
      grepl(
        "higher|associated",
        value
      )
  ) {
    return("higher_in_bacterial")
  }

  if (
    grepl("viral|virus", value) &&
      grepl(
        "higher|associated",
        value
      )
  ) {
    return("higher_in_viral")
  }

  stop(
    paste(
      "Unrecognized module direction:",
      direction_value
    )
  )
}


pairwise_difference_vector <- function(
  bacterial_scores,
  viral_scores
) {
  as.vector(
    outer(
      bacterial_scores,
      viral_scores,
      "-"
    )
  )
}


hodges_lehmann_shift <- function(
  bacterial_scores,
  viral_scores
) {
  median(
    pairwise_difference_vector(
      bacterial_scores,
      viral_scores
    )
  )
}


rank_biserial_from_pairwise <- function(
  bacterial_scores,
  viral_scores
) {
  differences <- pairwise_difference_vector(
    bacterial_scores,
    viral_scores
  )

  superiority_probability <- (
    sum(differences > 0) +
      0.5 * sum(differences == 0)
  ) / length(differences)

  2 * superiority_probability - 1
}


bootstrap_effect_sizes <- function(
  bacterial_scores,
  viral_scores,
  replicates,
  seed,
  ci_level,
  quantile_type
) {
  bacterial_n <- length(
    bacterial_scores
  )

  viral_n <- length(
    viral_scores
  )

  if (
    bacterial_n < 2L ||
      viral_n < 2L
  ) {
    stop(
      "Each bootstrap group must contain at least two observations."
    )
  }

  RNGkind(
    kind = "Mersenne-Twister",
    normal.kind = "Inversion",
    sample.kind = "Rejection"
  )

  set.seed(seed)

  hl_draws <- numeric(
    replicates
  )

  rank_biserial_draws <- numeric(
    replicates
  )

  for (bootstrap_index in seq_len(
    replicates
  )) {
    bacterial_bootstrap <- bacterial_scores[
      sample.int(
        bacterial_n,
        size = bacterial_n,
        replace = TRUE
      )
    ]

    viral_bootstrap <- viral_scores[
      sample.int(
        viral_n,
        size = viral_n,
        replace = TRUE
      )
    ]

    bootstrap_differences <- pairwise_difference_vector(
      bacterial_bootstrap,
      viral_bootstrap
    )

    hl_draws[bootstrap_index] <- median(
      bootstrap_differences
    )

    superiority_probability <- (
      sum(bootstrap_differences > 0) +
        0.5 *
          sum(bootstrap_differences == 0)
    ) / length(bootstrap_differences)

    rank_biserial_draws[bootstrap_index] <- (
      2 * superiority_probability - 1
    )
  }

  alpha <- 1 - ci_level

  probabilities <- c(
    alpha / 2,
    1 - alpha / 2
  )

  hl_interval <- as.numeric(
    quantile(
      hl_draws,
      probs = probabilities,
      names = FALSE,
      type = quantile_type,
      na.rm = TRUE
    )
  )

  rank_biserial_interval <- as.numeric(
    quantile(
      rank_biserial_draws,
      probs = probabilities,
      names = FALSE,
      type = quantile_type,
      na.rm = TRUE
    )
  )

  list(
    hl_ci_low =
      hl_interval[1L],
    hl_ci_high =
      hl_interval[2L],
    rank_biserial_ci_low =
      rank_biserial_interval[1L],
    rank_biserial_ci_high =
      rank_biserial_interval[2L],
    hl_bootstrap_mean =
      mean(hl_draws),
    hl_bootstrap_sd =
      sd(hl_draws),
    hl_bootstrap_minimum =
      min(hl_draws),
    hl_bootstrap_maximum =
      max(hl_draws),
    rank_biserial_bootstrap_mean =
      mean(rank_biserial_draws),
    rank_biserial_bootstrap_sd =
      sd(rank_biserial_draws),
    rank_biserial_bootstrap_minimum =
      min(rank_biserial_draws),
    rank_biserial_bootstrap_maximum =
      max(rank_biserial_draws),
    completed_replicates =
      length(hl_draws)
  )
}


confidence_interval_excludes_zero <- function(
  lower_bound,
  upper_bound
) {
  (
    lower_bound > 0 &&
      upper_bound > 0
  ) ||
    (
      lower_bound < 0 &&
        upper_bound < 0
    )
}


# -------------------------------------------------------------------------
# Validate required inputs
# -------------------------------------------------------------------------

required_files <- c(
  scores_file,
  reference_tests_file,
  analysis_manifest_file,
  coverage_file,
  projection_quality_summary_file
)

missing_files <- required_files[
  !file.exists(required_files)
]

if (length(missing_files) > 0L) {
  stop(
    paste(
      "Missing required input files:",
      paste(
        missing_files,
        collapse = ", "
      )
    )
  )
}


# -------------------------------------------------------------------------
# Read locked projection outputs
# -------------------------------------------------------------------------

message(
  "Reading locked GSE72810 projection outputs..."
)

scores <- fread(
  scores_file
)

reference_tests <- fread(
  reference_tests_file
)

analysis_manifest <- fread(
  analysis_manifest_file
)

coverage <- fread(
  coverage_file
)

projection_quality_summary <- fread(
  projection_quality_summary_file
)


# -------------------------------------------------------------------------
# Validate projection quality summary
# -------------------------------------------------------------------------

require_columns(
  projection_quality_summary,
  c(
    "total_checks",
    "passed_checks",
    "failed_checks",
    "score_rows",
    "test_rows",
    "group_summary_rows",
    "concordance_rows",
    "quality_gate",
    "projection_status"
  ),
  projection_quality_summary_file
)

if (nrow(projection_quality_summary) != 1L) {
  stop(
    "The projection quality summary must contain exactly one row."
  )
}

projection_quality_valid <- isTRUE(
  all(
    c(
      projection_quality_summary$
        total_checks[1L] ==
        21L,
      projection_quality_summary$
        passed_checks[1L] ==
        21L,
      projection_quality_summary$
        failed_checks[1L] ==
        0L,
      projection_quality_summary$
        score_rows[1L] ==
        expected_score_rows,
      projection_quality_summary$
        test_rows[1L] ==
        expected_reference_test_rows,
      projection_quality_summary$
        quality_gate[1L] ==
        "PASS",
      projection_quality_summary$
        projection_status[1L] ==
        "READY_FOR_EFFECT_SIZE_AND_FIGURE_ANALYSIS"
    )
  )
)

if (!projection_quality_valid) {
  stop(
    "The locked GSE72810 projection quality summary did not validate."
  )
}


# -------------------------------------------------------------------------
# Validate module scores
# -------------------------------------------------------------------------

require_columns(
  scores,
  c(
    "scoring_representation",
    "z_reference_population",
    "probe_collapse_rule",
    "geo_accession",
    "final_module_id",
    "final_module_label",
    "module_direction",
    "mapped_gene_count",
    "module_score",
    "sample_order",
    "category",
    "projection_role"
  ),
  scores_file
)

scores[
  ,
  geo_accession :=
    as.character(geo_accession)
]

scores[
  ,
  final_module_id :=
    as.character(final_module_id)
]

scores[
  ,
  category :=
    as.character(category)
]

scores[
  ,
  module_score :=
    as.numeric(module_score)
]

if (nrow(scores) != expected_score_rows) {
  stop(
    paste(
      "Expected",
      expected_score_rows,
      "module-score rows but recovered",
      nrow(scores)
    )
  )
}

if (
  anyNA(scores$module_score) ||
    any(!is.finite(scores$module_score))
) {
  stop(
    "The module-score table contains invalid scores."
  )
}

if (
  anyDuplicated(
    scores[
      ,
      .(
        scoring_representation,
        geo_accession,
        final_module_id
      )
    ]
  )
) {
  stop(
    "The module-score table contains duplicated keys."
  )
}

if (
  !setequal(
    unique(scores$final_module_id),
    expected_module_ids
  )
) {
  stop(
    "Unexpected module identifiers were found in the score table."
  )
}


# -------------------------------------------------------------------------
# Validate analysis manifest
# -------------------------------------------------------------------------

require_columns(
  analysis_manifest,
  c(
    "analysis_id",
    "analysis_role",
    "scoring_representation",
    "z_reference_population",
    "bacterial_categories",
    "viral_categories",
    "bacterial_n",
    "viral_n",
    "representative_probe_reselection",
    "module_reselection",
    "gene_reweighting",
    "module_renaming",
    "direction_flipping",
    "diagnostic_model_training"
  ),
  analysis_manifest_file
)

if (
  nrow(analysis_manifest) !=
    expected_manifest_rows ||
    anyDuplicated(
      analysis_manifest$analysis_id
    )
) {
  stop(
    "The analysis manifest failed row-count or uniqueness checks."
  )
}

if (!identical(
  analysis_manifest$analysis_id,
  expected_analysis_ids
)) {
  stop(
    "The analysis manifest order or identifiers do not match the lock."
  )
}

if (
  !all(
    analysis_manifest$
      representative_probe_reselection ==
      "Not permitted"
  ) ||
    !all(
      analysis_manifest$
        module_reselection ==
        "Not permitted"
    ) ||
    !all(
      analysis_manifest$
        gene_reweighting ==
        "Not permitted"
    ) ||
    !all(
      analysis_manifest$
        module_renaming ==
        "Not permitted"
    ) ||
    !all(
      analysis_manifest$
        direction_flipping ==
        "Not permitted"
    ) ||
    !all(
      analysis_manifest$
        diagnostic_model_training ==
        "Not permitted"
    )
) {
  stop(
    "At least one analysis manifest row violates the locked design."
  )
}


# -------------------------------------------------------------------------
# Validate reference statistical results
# -------------------------------------------------------------------------

require_columns(
  reference_tests,
  c(
    "analysis_id",
    "analysis_role",
    "scoring_representation",
    "z_reference_population",
    "probe_collapse_rule",
    "final_module_id",
    "final_module_label",
    "expected_direction_raw",
    "expected_direction",
    "observed_direction",
    "direction_retained",
    "bacterial_n",
    "viral_n",
    "mean_bacterial",
    "mean_viral",
    "mean_difference_bacterial_minus_viral",
    "median_bacterial",
    "median_viral",
    "median_difference_bacterial_minus_viral",
    "wilcoxon_u",
    "rank_biserial_effect",
    "wilcoxon_p",
    "wilcoxon_q",
    "nominal_significant",
    "fdr_significant"
  ),
  reference_tests_file
)

reference_tests[
  ,
  direction_retained :=
    coerce_logical_strict(
      direction_retained,
      "reference_tests$direction_retained"
    )
]

reference_tests[
  ,
  nominal_significant :=
    coerce_logical_strict(
      nominal_significant,
      "reference_tests$nominal_significant"
    )
]

reference_tests[
  ,
  fdr_significant :=
    coerce_logical_strict(
      fdr_significant,
      "reference_tests$fdr_significant"
    )
]

if (
  nrow(reference_tests) !=
    expected_reference_test_rows ||
    anyDuplicated(
      reference_tests[
        ,
        .(
          analysis_id,
          final_module_id
        )
      ]
    )
) {
  stop(
    "The reference test table failed row-count or uniqueness checks."
  )
}

if (
  !setequal(
    unique(reference_tests$analysis_id),
    expected_analysis_ids
  ) ||
    !setequal(
      unique(reference_tests$final_module_id),
      expected_module_ids
    )
) {
  stop(
    "The reference test table does not contain the locked analyses and modules."
  )
}


# -------------------------------------------------------------------------
# Validate coverage
# -------------------------------------------------------------------------

require_columns(
  coverage,
  c(
    "final_module_id",
    "final_module_label",
    "module_direction",
    "locked_gene_count",
    "mapped_gene_count",
    "missing_gene_count",
    "coverage_fraction",
    "missing_symbols",
    "representative_probes_frozen"
  ),
  coverage_file
)

coverage[
  ,
  representative_probes_frozen :=
    coerce_logical_strict(
      representative_probes_frozen,
      "coverage$representative_probes_frozen"
    )
]

if (
  nrow(coverage) !=
    expected_coverage_rows ||
    !setequal(
      coverage$final_module_id,
      expected_module_ids
    ) ||
    !all(
      coverage$coverage_fraction >=
        0.70
    ) ||
    !all(
      coverage$representative_probes_frozen
    )
) {
  stop(
    "The module-coverage table did not validate."
  )
}


# -------------------------------------------------------------------------
# Calculate effect sizes and bootstrap confidence intervals
# -------------------------------------------------------------------------

message(
  "Calculating effect sizes and 10,000-replicate confidence intervals..."
)

effect_rows <- vector(
  "list",
  expected_effect_rows
)

bootstrap_rows <- vector(
  "list",
  expected_effect_rows
)

result_index <- 0L

for (analysis_index in seq_len(
  nrow(analysis_manifest)
)) {
  current_manifest <- analysis_manifest[
    analysis_index
  ]

  analysis_id <- current_manifest$
    analysis_id

  representation_id <- current_manifest$
    scoring_representation

  bacterial_categories <- parse_semicolon_values(
    current_manifest$
      bacterial_categories
  )

  viral_categories <- parse_semicolon_values(
    current_manifest$
      viral_categories
  )

  expected_bacterial_n <- as.integer(
    current_manifest$
      bacterial_n
  )

  expected_viral_n <- as.integer(
    current_manifest$
      viral_n
  )

  analysis_scores <- scores[
    scoring_representation ==
      representation_id
  ]

  for (module_index in seq_along(
    expected_module_ids
  )) {
    result_index <- result_index + 1L

    module_id <- expected_module_ids[
      module_index
    ]

    message(
      paste0(
        "[",
        result_index,
        "/",
        expected_effect_rows,
        "] ",
        analysis_id,
        " / ",
        module_id
      )
    )

    module_scores <- analysis_scores[
      final_module_id ==
        module_id
    ]

    bacterial_scores <- module_scores[
      category %in%
        bacterial_categories,
      module_score
    ]

    viral_scores <- module_scores[
      category %in%
        viral_categories,
      module_score
    ]

    if (
      length(bacterial_scores) !=
        expected_bacterial_n ||
        length(viral_scores) !=
          expected_viral_n
    ) {
      stop(
        paste(
          "Unexpected group counts for",
          analysis_id,
          module_id,
          ": bacterial",
          length(bacterial_scores),
          "viral",
          length(viral_scores)
        )
      )
    }

    if (
      anyNA(bacterial_scores) ||
        anyNA(viral_scores) ||
        any(!is.finite(bacterial_scores)) ||
        any(!is.finite(viral_scores))
    ) {
      stop(
        paste(
          "Invalid scores detected for",
          analysis_id,
          module_id
        )
      )
    }

    expected_direction_raw <- module_scores$
      module_direction[1L]

    expected_direction <- normalize_expected_direction(
      expected_direction_raw
    )

    mean_bacterial <- mean(
      bacterial_scores
    )

    mean_viral <- mean(
      viral_scores
    )

    mean_difference <- (
      mean_bacterial -
        mean_viral
    )

    median_bacterial <- median(
      bacterial_scores
    )

    median_viral <- median(
      viral_scores
    )

    median_difference <- (
      median_bacterial -
        median_viral
    )

    hl_estimate <- hodges_lehmann_shift(
      bacterial_scores,
      viral_scores
    )

    wilcoxon_result <- suppressWarnings(
      wilcox.test(
        bacterial_scores,
        viral_scores,
        alternative = "two.sided",
        exact = FALSE
      )
    )

    wilcoxon_u <- as.numeric(
      wilcoxon_result$statistic
    )

    rank_biserial_from_u <- (
      2 * wilcoxon_u /
        (
          length(bacterial_scores) *
            length(viral_scores)
        )
    ) - 1

    rank_biserial_pairwise <- rank_biserial_from_pairwise(
      bacterial_scores,
      viral_scores
    )

    if (
      abs(
        rank_biserial_from_u -
          rank_biserial_pairwise
      ) >
        comparison_tolerance
    ) {
      stop(
        paste(
          "Rank-biserial implementations disagree for",
          analysis_id,
          module_id
        )
      )
    }

    observed_direction <- if (
      median_difference > 0
    ) {
      "higher_in_bacterial"
    } else if (
      median_difference < 0
    ) {
      "higher_in_viral"
    } else {
      "no_median_difference"
    }

    direction_retained <- (
      observed_direction ==
        expected_direction
    )

    bootstrap_seed <- (
      base_seed +
        analysis_index * 100L +
        module_index
    )

    bootstrap_result <- bootstrap_effect_sizes(
      bacterial_scores =
        bacterial_scores,
      viral_scores =
        viral_scores,
      replicates =
        bootstrap_replicates,
      seed =
        bootstrap_seed,
      ci_level =
        bootstrap_ci_level,
      quantile_type =
        bootstrap_quantile_type
    )

    hl_ci_excludes_zero <- confidence_interval_excludes_zero(
      bootstrap_result$hl_ci_low,
      bootstrap_result$hl_ci_high
    )

    rank_biserial_ci_excludes_zero <-
      confidence_interval_excludes_zero(
        bootstrap_result$
          rank_biserial_ci_low,
        bootstrap_result$
          rank_biserial_ci_high
      )

    effect_rows[[result_index]] <- data.table(
      analysis_id =
        analysis_id,
      analysis_role =
        current_manifest$
          analysis_role,
      scoring_representation =
        representation_id,
      z_reference_population =
        current_manifest$
          z_reference_population,
      bacterial_categories =
        current_manifest$
          bacterial_categories,
      viral_categories =
        current_manifest$
          viral_categories,
      final_module_id =
        module_id,
      final_module_label =
        module_scores$
          final_module_label[1L],
      expected_direction_raw =
        expected_direction_raw,
      expected_direction =
        expected_direction,
      observed_direction =
        observed_direction,
      direction_retained =
        direction_retained,
      bacterial_n =
        length(bacterial_scores),
      viral_n =
        length(viral_scores),
      mean_bacterial =
        mean_bacterial,
      mean_viral =
        mean_viral,
      mean_difference_bacterial_minus_viral =
        mean_difference,
      median_bacterial =
        median_bacterial,
      median_viral =
        median_viral,
      median_difference_bacterial_minus_viral =
        median_difference,
      hodges_lehmann_shift_bacterial_minus_viral =
        hl_estimate,
      hodges_lehmann_ci_low =
        bootstrap_result$
          hl_ci_low,
      hodges_lehmann_ci_high =
        bootstrap_result$
          hl_ci_high,
      hodges_lehmann_ci_excludes_zero =
        hl_ci_excludes_zero,
      wilcoxon_u =
        wilcoxon_u,
      rank_biserial_effect =
        rank_biserial_from_u,
      rank_biserial_ci_low =
        bootstrap_result$
          rank_biserial_ci_low,
      rank_biserial_ci_high =
        bootstrap_result$
          rank_biserial_ci_high,
      rank_biserial_ci_excludes_zero =
        rank_biserial_ci_excludes_zero,
      wilcoxon_p =
        wilcoxon_result$p.value,
      bootstrap_ci_method =
        paste0(
          "Stratified nonparametric percentile bootstrap; ",
          bootstrap_replicates,
          " replicates"
        ),
      bootstrap_ci_level =
        bootstrap_ci_level,
      bootstrap_quantile_type =
        bootstrap_quantile_type,
      bootstrap_seed =
        bootstrap_seed,
      bootstrap_replicates_completed =
        bootstrap_result$
          completed_replicates
    )

    bootstrap_rows[[result_index]] <- data.table(
      analysis_id =
        analysis_id,
      final_module_id =
        module_id,
      bacterial_n =
        length(bacterial_scores),
      viral_n =
        length(viral_scores),
      bootstrap_seed =
        bootstrap_seed,
      requested_replicates =
        bootstrap_replicates,
      completed_replicates =
        bootstrap_result$
          completed_replicates,
      ci_level =
        bootstrap_ci_level,
      quantile_type =
        bootstrap_quantile_type,
      hl_bootstrap_mean =
        bootstrap_result$
          hl_bootstrap_mean,
      hl_bootstrap_sd =
        bootstrap_result$
          hl_bootstrap_sd,
      hl_bootstrap_minimum =
        bootstrap_result$
          hl_bootstrap_minimum,
      hl_bootstrap_maximum =
        bootstrap_result$
          hl_bootstrap_maximum,
      rank_biserial_bootstrap_mean =
        bootstrap_result$
          rank_biserial_bootstrap_mean,
      rank_biserial_bootstrap_sd =
        bootstrap_result$
          rank_biserial_bootstrap_sd,
      rank_biserial_bootstrap_minimum =
        bootstrap_result$
          rank_biserial_bootstrap_minimum,
      rank_biserial_bootstrap_maximum =
        bootstrap_result$
          rank_biserial_bootstrap_maximum
    )
  }
}

effect_results <- rbindlist(
  effect_rows,
  use.names = TRUE,
  fill = TRUE
)

bootstrap_manifest <- rbindlist(
  bootstrap_rows,
  use.names = TRUE,
  fill = TRUE
)


# -------------------------------------------------------------------------
# Calculate within-analysis FDR
# -------------------------------------------------------------------------

effect_results[
  ,
  wilcoxon_q :=
    p.adjust(
      wilcoxon_p,
      method = "BH"
    ),
  by = analysis_id
]

effect_results[
  ,
  nominal_significant :=
    wilcoxon_p < 0.05
]

effect_results[
  ,
  fdr_significant :=
    wilcoxon_q < 0.05
]


# -------------------------------------------------------------------------
# Merge and compare against Script 47 reference results
# -------------------------------------------------------------------------

reference_comparison <- reference_tests[
  ,
  .(
    analysis_id,
    final_module_id,
    reference_bacterial_n =
      bacterial_n,
    reference_viral_n =
      viral_n,
    reference_mean_bacterial =
      mean_bacterial,
    reference_mean_viral =
      mean_viral,
    reference_mean_difference =
      mean_difference_bacterial_minus_viral,
    reference_median_bacterial =
      median_bacterial,
    reference_median_viral =
      median_viral,
    reference_median_difference =
      median_difference_bacterial_minus_viral,
    reference_wilcoxon_u =
      wilcoxon_u,
    reference_rank_biserial =
      rank_biserial_effect,
    reference_wilcoxon_p =
      wilcoxon_p,
    reference_wilcoxon_q =
      wilcoxon_q,
    reference_observed_direction =
      observed_direction,
    reference_direction_retained =
      direction_retained,
    reference_nominal_significant =
      nominal_significant,
    reference_fdr_significant =
      fdr_significant
  )
]

effect_results <- merge(
  effect_results,
  reference_comparison,
  by = c(
    "analysis_id",
    "final_module_id"
  ),
  all.x = TRUE,
  sort = FALSE
)

if (
  anyNA(
    effect_results$
      reference_bacterial_n
  )
) {
  stop(
    "The effect-size results did not merge completely with Script 47."
  )
}

effect_results[
  ,
  bacterial_n_matches_reference :=
    bacterial_n ==
      reference_bacterial_n
]

effect_results[
  ,
  viral_n_matches_reference :=
    viral_n ==
      reference_viral_n
]

effect_results[
  ,
  mean_bacterial_abs_difference :=
    abs(
      mean_bacterial -
        reference_mean_bacterial
    )
]

effect_results[
  ,
  mean_viral_abs_difference :=
    abs(
      mean_viral -
        reference_mean_viral
    )
]

effect_results[
  ,
  mean_difference_abs_difference :=
    abs(
      mean_difference_bacterial_minus_viral -
        reference_mean_difference
    )
]

effect_results[
  ,
  median_bacterial_abs_difference :=
    abs(
      median_bacterial -
        reference_median_bacterial
    )
]

effect_results[
  ,
  median_viral_abs_difference :=
    abs(
      median_viral -
        reference_median_viral
    )
]

effect_results[
  ,
  median_difference_abs_difference :=
    abs(
      median_difference_bacterial_minus_viral -
        reference_median_difference
    )
]

effect_results[
  ,
  wilcoxon_u_abs_difference :=
    abs(
      wilcoxon_u -
        reference_wilcoxon_u
    )
]

effect_results[
  ,
  rank_biserial_abs_difference :=
    abs(
      rank_biserial_effect -
        reference_rank_biserial
    )
]

effect_results[
  ,
  wilcoxon_p_abs_difference :=
    abs(
      wilcoxon_p -
        reference_wilcoxon_p
    )
]

effect_results[
  ,
  wilcoxon_q_abs_difference :=
    abs(
      wilcoxon_q -
        reference_wilcoxon_q
    )
]

effect_results[
  ,
  observed_direction_matches_reference :=
    observed_direction ==
      reference_observed_direction
]

effect_results[
  ,
  direction_retained_matches_reference :=
    direction_retained ==
      reference_direction_retained
]

effect_results[
  ,
  nominal_significance_matches_reference :=
    nominal_significant ==
      reference_nominal_significant
]

effect_results[
  ,
  fdr_significance_matches_reference :=
    fdr_significant ==
      reference_fdr_significant
]


# -------------------------------------------------------------------------
# Restore locked row order
# -------------------------------------------------------------------------

effect_results[
  ,
  analysis_order :=
    match(
      analysis_id,
      expected_analysis_ids
    )
]

effect_results[
  ,
  module_order :=
    match(
      final_module_id,
      expected_module_ids
    )
]

setorder(
  effect_results,
  analysis_order,
  module_order
)

effect_results[
  ,
  c(
    "analysis_order",
    "module_order"
  ) := NULL
]

bootstrap_manifest[
  ,
  analysis_order :=
    match(
      analysis_id,
      expected_analysis_ids
    )
]

bootstrap_manifest[
  ,
  module_order :=
    match(
      final_module_id,
      expected_module_ids
    )
]

setorder(
  bootstrap_manifest,
  analysis_order,
  module_order
)

bootstrap_manifest[
  ,
  c(
    "analysis_order",
    "module_order"
  ) := NULL
]


# -------------------------------------------------------------------------
# Manuscript-ready primary table
# -------------------------------------------------------------------------

primary_table <- effect_results[
  analysis_id ==
    "main_representative_all146_z_definite",
  .(
    final_module_id,
    final_module_label,
    expected_direction,
    bacterial_n,
    viral_n,
    median_bacterial,
    median_viral,
    median_difference_bacterial_minus_viral,
    hodges_lehmann_shift_bacterial_minus_viral,
    hodges_lehmann_ci_low,
    hodges_lehmann_ci_high,
    hodges_lehmann_ci_excludes_zero,
    rank_biserial_effect,
    rank_biserial_ci_low,
    rank_biserial_ci_high,
    rank_biserial_ci_excludes_zero,
    wilcoxon_p,
    wilcoxon_q,
    direction_retained,
    fdr_significant
  )
]


# -------------------------------------------------------------------------
# Analysis-level summary
# -------------------------------------------------------------------------

analysis_summary <- effect_results[
  ,
  .(
    module_count = .N,
    direction_retained_modules =
      sum(direction_retained),
    nominally_significant_modules =
      sum(nominal_significant),
    fdr_significant_modules =
      sum(fdr_significant),
    hodges_lehmann_ci_excluding_zero_modules =
      sum(
        hodges_lehmann_ci_excludes_zero
      ),
    rank_biserial_ci_excluding_zero_modules =
      sum(
        rank_biserial_ci_excludes_zero
      ),
    minimum_hodges_lehmann_shift =
      min(
        hodges_lehmann_shift_bacterial_minus_viral
      ),
    maximum_hodges_lehmann_shift =
      max(
        hodges_lehmann_shift_bacterial_minus_viral
      ),
    minimum_rank_biserial_effect =
      min(rank_biserial_effect),
    maximum_rank_biserial_effect =
      max(rank_biserial_effect)
  ),
  by = .(
    analysis_id,
    analysis_role,
    scoring_representation,
    z_reference_population
  )
]

analysis_summary[
  ,
  analysis_order :=
    match(
      analysis_id,
      expected_analysis_ids
    )
]

setorder(
  analysis_summary,
  analysis_order
)

analysis_summary[
  ,
  analysis_order := NULL
]


# -------------------------------------------------------------------------
# Quality gate
# -------------------------------------------------------------------------

effect_keys_unique <- !anyDuplicated(
  effect_results[
    ,
    .(
      analysis_id,
      final_module_id
    )
  ]
)

bootstrap_keys_unique <- !anyDuplicated(
  bootstrap_manifest[
    ,
    .(
      analysis_id,
      final_module_id
    )
  ]
)

all_reference_counts_match <- all(
  effect_results$
    bacterial_n_matches_reference
) &&
  all(
    effect_results$
      viral_n_matches_reference
  )

all_reference_summaries_match <- all(
  effect_results$
    mean_bacterial_abs_difference <=
    comparison_tolerance
) &&
  all(
    effect_results$
      mean_viral_abs_difference <=
      comparison_tolerance
  ) &&
  all(
    effect_results$
      mean_difference_abs_difference <=
      comparison_tolerance
  ) &&
  all(
    effect_results$
      median_bacterial_abs_difference <=
      comparison_tolerance
  ) &&
  all(
    effect_results$
      median_viral_abs_difference <=
      comparison_tolerance
  ) &&
  all(
    effect_results$
      median_difference_abs_difference <=
      comparison_tolerance
  )

all_reference_statistics_match <- all(
  effect_results$
    wilcoxon_u_abs_difference <=
    comparison_tolerance
) &&
  all(
    effect_results$
      rank_biserial_abs_difference <=
      comparison_tolerance
  ) &&
  all(
    effect_results$
      wilcoxon_p_abs_difference <=
      comparison_tolerance
  ) &&
  all(
    effect_results$
      wilcoxon_q_abs_difference <=
      comparison_tolerance
  )

all_reference_labels_match <- all(
  effect_results$
    observed_direction_matches_reference
) &&
  all(
    effect_results$
      direction_retained_matches_reference
  ) &&
  all(
    effect_results$
      nominal_significance_matches_reference
  ) &&
  all(
    effect_results$
      fdr_significance_matches_reference
  )

all_bootstraps_complete <- all(
  effect_results$
    bootstrap_replicates_completed ==
    bootstrap_replicates
) &&
  all(
    bootstrap_manifest$
      completed_replicates ==
      bootstrap_replicates
  )

all_intervals_finite <- all(
  is.finite(
    effect_results$
      hodges_lehmann_ci_low
  )
) &&
  all(
    is.finite(
      effect_results$
        hodges_lehmann_ci_high
    )
  ) &&
  all(
    is.finite(
      effect_results$
        rank_biserial_ci_low
    )
  ) &&
  all(
    is.finite(
      effect_results$
        rank_biserial_ci_high
    )
  )

all_interval_order_valid <- all(
  effect_results$
    hodges_lehmann_ci_low <=
    effect_results$
      hodges_lehmann_ci_high
) &&
  all(
    effect_results$
      rank_biserial_ci_low <=
    effect_results$
      rank_biserial_ci_high
  )

all_rank_biserial_bounds_valid <- all(
  effect_results$
    rank_biserial_effect >=
    -1
) &&
  all(
    effect_results$
      rank_biserial_effect <=
      1
  ) &&
  all(
    effect_results$
      rank_biserial_ci_low >=
      -1
  ) &&
  all(
    effect_results$
      rank_biserial_ci_high <=
      1
  )

all_seeds_unique <- (
  uniqueN(
    bootstrap_manifest$
      bootstrap_seed
  ) ==
    expected_effect_rows
)

quality_checks <- data.table(
  check_id = sprintf(
    "Q%02d",
    seq_len(18L)
  ),
  check_description = c(
    "Locked Script 47 projection quality summary validates",
    "Module-score input contains 1,715 rows",
    "Module-score keys are unique and finite",
    "Analysis manifest contains four locked analyses",
    "Reference test input contains 20 unique rows",
    "Coverage input contains five eligible frozen modules",
    "Twenty effect-size rows were generated",
    "Five primary manuscript-table rows were generated",
    "Twenty bootstrap-manifest rows were generated",
    "Effect-size keys are unique",
    "Bootstrap-manifest keys and seeds are unique",
    "All group counts match Script 47",
    "All recomputed group summaries match Script 47",
    "All recomputed test statistics and adjusted P values match Script 47",
    "All direction and significance labels match Script 47",
    "All 10,000 bootstrap replicates completed for every row",
    "All confidence intervals are finite and correctly ordered",
    "All rank-biserial estimates and intervals remain within minus one and one"
  ),
  pass = c(
    projection_quality_valid,
    nrow(scores) ==
      expected_score_rows,
    !anyDuplicated(
      scores[
        ,
        .(
          scoring_representation,
          geo_accession,
          final_module_id
        )
      ]
    ) &&
      !anyNA(scores$module_score) &&
      all(
        is.finite(scores$module_score)
      ),
    nrow(analysis_manifest) ==
      expected_manifest_rows &&
      identical(
        analysis_manifest$
          analysis_id,
        expected_analysis_ids
      ),
    nrow(reference_tests) ==
      expected_reference_test_rows &&
      !anyDuplicated(
        reference_tests[
          ,
          .(
            analysis_id,
            final_module_id
          )
        ]
      ),
    nrow(coverage) ==
      expected_coverage_rows &&
      all(
        coverage$coverage_fraction >=
          0.70
      ) &&
      all(
        coverage$
          representative_probes_frozen
      ),
    nrow(effect_results) ==
      expected_effect_rows,
    nrow(primary_table) ==
      expected_primary_rows,
    nrow(bootstrap_manifest) ==
      expected_effect_rows,
    effect_keys_unique,
    bootstrap_keys_unique &&
      all_seeds_unique,
    all_reference_counts_match,
    all_reference_summaries_match,
    all_reference_statistics_match,
    all_reference_labels_match,
    all_bootstraps_complete,
    all_intervals_finite &&
      all_interval_order_valid,
    all_rank_biserial_bounds_valid
  )
)

quality_gate_pass <- all(
  quality_checks$pass
)

quality_summary <- data.table(
  total_checks =
    nrow(quality_checks),
  passed_checks =
    sum(quality_checks$pass),
  failed_checks =
    sum(!quality_checks$pass),
  effect_size_rows =
    nrow(effect_results),
  primary_table_rows =
    nrow(primary_table),
  bootstrap_manifest_rows =
    nrow(bootstrap_manifest),
  bootstrap_replicates_per_row =
    bootstrap_replicates,
  total_bootstrap_replicates =
    sum(
      bootstrap_manifest$
        completed_replicates
    ),
  direction_retained_rows =
    sum(
      effect_results$
        direction_retained
    ),
  nominally_significant_rows =
    sum(
      effect_results$
        nominal_significant
    ),
  fdr_significant_rows =
    sum(
      effect_results$
        fdr_significant
    ),
  hodges_lehmann_ci_excluding_zero_rows =
    sum(
      effect_results$
        hodges_lehmann_ci_excludes_zero
    ),
  rank_biserial_ci_excluding_zero_rows =
    sum(
      effect_results$
        rank_biserial_ci_excludes_zero
    ),
  quality_gate =
    ifelse(
      quality_gate_pass,
      "PASS",
      "REVIEW"
    ),
  analysis_status =
    ifelse(
      quality_gate_pass,
      "READY_FOR_GSE72810_FIGURE_AND_MANUSCRIPT_INTEGRATION",
      "EFFECT_SIZE_ANALYSIS_REVIEW_REQUIRED"
    )
)


# -------------------------------------------------------------------------
# Write output tables
# -------------------------------------------------------------------------

fwrite(
  effect_results,
  effect_results_file,
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  primary_table,
  primary_table_file,
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  bootstrap_manifest,
  bootstrap_manifest_file,
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  analysis_summary,
  analysis_summary_file,
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  quality_checks,
  quality_checks_file,
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  quality_summary,
  quality_summary_file,
  sep = "\t",
  quote = FALSE,
  na = "NA"
)


# -------------------------------------------------------------------------
# Report
# -------------------------------------------------------------------------

primary_preview <- capture.output(
  print(
    primary_table[
      ,
      .(
        final_module_id,
        bacterial_n,
        viral_n,
        median_difference_bacterial_minus_viral,
        hodges_lehmann_shift_bacterial_minus_viral,
        hodges_lehmann_ci_low,
        hodges_lehmann_ci_high,
        rank_biserial_effect,
        rank_biserial_ci_low,
        rank_biserial_ci_high,
        wilcoxon_p,
        wilcoxon_q,
        direction_retained,
        fdr_significant
      )
    ]
  )
)

analysis_preview <- capture.output(
  print(analysis_summary)
)

quality_preview <- capture.output(
  print(quality_checks)
)

report_lines <- c(
  "# GSE72810 effect sizes and confidence intervals",
  "",
  "## Analytical framework",
  "",
  paste(
    "Effect sizes were calculated for the primary GSE72810",
    "projection and its three prespecified sensitivities without",
    "changing the frozen probes, locked module memberships, sample",
    "definitions, z-reference definitions or expected directions."
  ),
  "",
  paste(
    "The Hodges-Lehmann estimate is the median of all pairwise",
    "bacterial-minus-viral score differences. Positive estimates",
    "indicate higher scores in bacterial samples, whereas negative",
    "estimates indicate higher scores in viral samples."
  ),
  "",
  paste(
    "Rank-biserial effects range from minus one to one. Positive",
    "values indicate greater bacterial scores and negative values",
    "indicate greater viral scores."
  ),
  "",
  paste(
    "Confidence intervals used stratified nonparametric percentile",
    "bootstrap resampling within bacterial and viral groups with",
    "10,000 replicates per analysis-module combination."
  ),
  "",
  "## Primary-analysis effect sizes",
  "",
  "```text",
  primary_preview,
  "```",
  "",
  "## Analysis-level summary",
  "",
  "```text",
  analysis_preview,
  "```",
  "",
  "## Quality gate",
  "",
  "```text",
  quality_preview,
  "```",
  "",
  paste0(
    "- Quality gate: `",
    quality_summary$quality_gate,
    "`."
  ),
  paste0(
    "- Analysis status: `",
    quality_summary$analysis_status,
    "`."
  ),
  paste0(
    "- Total completed bootstrap replicates: ",
    format(
      quality_summary$
        total_bootstrap_replicates,
      big.mark = ",",
      scientific = FALSE
    ),
    "."
  )
)

writeLines(
  report_lines,
  report_file
)


# -------------------------------------------------------------------------
# Session information
# -------------------------------------------------------------------------

session_lines <- capture.output(
  sessionInfo()
)

session_lines <- sub(
  "[ \t]+$",
  "",
  session_lines
)

writeLines(
  session_lines,
  session_file
)


# -------------------------------------------------------------------------
# Console summary
# -------------------------------------------------------------------------

cat(
  "===== GSE72810 EFFECT SIZES AND CONFIDENCE INTERVALS =====\n"
)

cat(
  "analyses\t",
  nrow(analysis_manifest),
  "\n",
  sep = ""
)

cat(
  "modules\t",
  length(expected_module_ids),
  "\n",
  sep = ""
)

cat(
  "effect_size_rows\t",
  nrow(effect_results),
  "\n",
  sep = ""
)

cat(
  "bootstrap_replicates_per_row\t",
  bootstrap_replicates,
  "\n",
  sep = ""
)

cat(
  "total_bootstrap_replicates\t",
  sum(
    bootstrap_manifest$
      completed_replicates
  ),
  "\n",
  sep = ""
)

cat(
  "quality_checks_passed\t",
  sum(quality_checks$pass),
  "/",
  nrow(quality_checks),
  "\n",
  sep = ""
)

cat(
  "quality_gate\t",
  quality_summary$quality_gate,
  "\n",
  sep = ""
)

cat(
  "analysis_status\t",
  quality_summary$analysis_status,
  "\n",
  sep = ""
)

cat(
  "\n===== ANALYSIS SUMMARY =====\n"
)

print(
  analysis_summary
)

cat(
  "\neffect_results\t",
  effect_results_file,
  "\n",
  sep = ""
)

cat(
  "primary_table\t",
  primary_table_file,
  "\n",
  sep = ""
)

cat(
  "bootstrap_manifest\t",
  bootstrap_manifest_file,
  "\n",
  sep = ""
)

cat(
  "quality_summary\t",
  quality_summary_file,
  "\n",
  sep = ""
)

cat(
  "report\t",
  report_file,
  "\n",
  sep = ""
)

if (!quality_gate_pass) {
  stop(
    "The GSE72810 effect-size analysis failed its quality gate."
  )
}
